baseURL = "http://kodebot.github.io/learn.kodebot.github.io"
languageCode = "en-GB"
title = "kodebot learning"
theme = "hugo-theme-learn"
publishDir = "docs"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"
