baseURL = "http://localhost/kodebot"
languageCode = "en-GB"
title = "kodebot"
theme = "hugo-theme-learn"
publishDir = "docs"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"