baseURL = "https://kodebot.com/"
languageCode = "en-GB"
title = "Kodebot"
theme = "hugo-theme-learn"
publishDir = "docs"
enableEmoji = true

pygmentsCodeFences= true

disqusShortname="kodebot"
googleAnalytics="UA-146320930-1"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"